version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_URL: "http://user-service:8081"
      PRODUCT_SERVICE_URL: "http://product-service:8082"
      ORDER_SERVICE_URL: "http://order-service:8083"
      PAYMENT_SERVICE_URL: "http://payment-service:8084"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: h2
    depends_on:
      - api-gateway

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: h2
    depends_on:
      - api-gateway

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: h2
    depends_on:
      - api-gateway

  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: h2
    depends_on:
      - api-gateway
