server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: ${user.service.url}
          predicates:
            - Path=/api/v1/user/**

        - id: product-service
          uri: ${product.service.url}
          predicates:
            - Path=/api/v1/product/**

        - id: order-service
          uri: ${order.service.url}
          predicates:
            - Path=/api/v1/orders/**

        - id: payment-service
          uri: ${payment.service.url}
          predicates:
            - Path=/api/v1/payments/**

user:
  service:
    url: http://user-service:8081

product:
  service:
    url: http://product-service:8082

order:
  service:
    url: http://order-service:8083

payment:
  service:
    url: http://payment-service:8084

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    operationsSorter: alpha
    tagsSorter: alpha
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /user-service/v3/api-docs
        name: User Service
        primaryName: User Service
      - url: /product-service/v3/api-docs
        name: Product Service
        primaryName: Product Service
      - url: /order-service/v3/api-docs
        name: Order Service
        primaryName: Order Service
      - url: /payment-service/v3/api-docs
        name: Payment Service
        primaryName: Payment Service